### ISSUE TITLE
DCAF Core should auto-include Table API.  It currently does not.

### ISSUE THREAD

**Issue by pollockm** [LabVIEW-DCAF/DCAF-Core#3]
Install only DCAF Core on a clean system.  Try to create a new instance of the templates.  They fail due to Table API not being installed.

Need to include DCAF Table API as a dependency.  Not sure if it should be a direct dependency of DCAF Core or of the DCAF Project Templates.

**Comment by becega** [comment]
TEmplates need to be updated. Table API is not part of Tag Editor Core
https://github.com/LabVIEW-DCAF/DCAF-Project-Templates/issues/56

**Comment by pollockm** [comment]
Documenting since I was confused: the DCAF Table API package is now deprecated and should not be installed (or linked against), since the entire table api codebase has been included in TagEditorCore rather than a separate package.
